# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HEGSRR
subtitle: Reproducibility & Replicability in Geography
# email:
description: >- # this means to ignore newlines until "baseurl:"
  Human-Environment and Geographical Sciences Reproducibility and Replicability
# twitter_username: username
github_username: HEGSRR
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# icons are from https://fontawesome.com/v5/search

author:
  name   : "Peter Kedron and Joseph Holler"
  avatar : "/assets/images/nsf.png"
  bio    : "Transforming Theory and STEM Education Through Reproductions and Replications in the Geographical Sciences"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/HEGSRR"
    - label: "OSF"
      icon: "fas fa-cube"
      url: "https://osf.io/c5a2r/"
    - label: "Dr Kedron"
      icon: "fas fa-fw fa-link"
      url: "https://peterkedron.com/"
    - label: "Dr Holler"
      icon: "fas fa-fw fa-link"
      url: "https://josephholler.github.io/"
    - label: "Open GIScience"
      icon: "fab fa-fw fa-github"
      url: "https://opengisci.github.io/"

footer:
  links:
    - label: "NSF Award 2049837"
      #icon: "fab fa-fw fa-twitter-square"
      url: "https://www.nsf.gov/awardsearch/showAward?AWD_ID=2049837"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HEGSRR"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

timezone: America/New_York
future: true
